targets:
  $default:
    builders:
      riverpod_generator:
        generate_for:
          - lib/src/main/providers/**.dart
          - lib/src/presentation/notifiers/**.dart
          - lib/src/presentation/**/notifiers/**.dart
