// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case .android:
        return android;
      case .iOS:
        return ios;
      case .macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case .windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case .linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    projectId: 'trocado-8ed2c',
    messagingSenderId: '1005231773965',
    apiKey: 'AIzaSyApU1vlgpfjsj8pmMeZFBonJ-CXkgxKnj4',
    storageBucket: 'trocado-8ed2c.firebasestorage.app',
    appId: '1:1005231773965:android:0b24137d24073e6f2ff844',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    projectId: 'trocado-8ed2c',
    iosBundleId: 'br.com.bed.trocado',
    messagingSenderId: '1005231773965',
    apiKey: 'AIzaSyC5WN89baG_wSsr6Yj_nY-IQ5wK5EWmSZI',
    appId: '1:1005231773965:ios:8bdada161b12755d2ff844',
    storageBucket: 'trocado-8ed2c.firebasestorage.app',
  );
}
