// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'src/infrastructure/clients/database/entities/budget_entity.dart';
import 'src/infrastructure/clients/database/entities/expense_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 5353104918585052881),
    name: 'ExpenseEntity',
    lastPropertyId: const obx_int.IdUid(5, 5677225363591521911),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4401769687359133975),
        name: 'date',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1439559730341620322),
        name: 'amount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 683469373526493450),
        name: 'category',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4534146325090464610),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5677225363591521911),
        name: 'id',
        type: 6,
        flags: 1,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 9134741375688702267),
    name: 'BudgetEntity',
    lastPropertyId: const obx_int.IdUid(5, 1624905594375077018),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8306207677289473670),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5821562572562123966),
        name: 'amount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2232114485359185188),
        name: 'startDate',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2453380748853350183),
        name: 'endDate',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1624905594375077018),
        name: 'description',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 9134741375688702267),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [1852755316315486217],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      8914437015231901503,
      1052695545010608414,
      124474464062880185,
      6359883799787194156,
      3291498247467525613,
      7680930992602820770,
      8136152323425421718,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ExpenseEntity: obx_int.EntityDefinition<ExpenseEntity>(
      model: _entities[0],
      toOneRelations: (ExpenseEntity object) => [],
      toManyRelations: (ExpenseEntity object) => {},
      getId: (ExpenseEntity object) => object.id,
      setId: (ExpenseEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ExpenseEntity object, fb.Builder fbb) {
        final categoryOffset = fbb.writeString(object.category);
        final descriptionOffset = fbb.writeString(object.description);
        fbb.startTable(6);
        fbb.addInt64(0, object.date);
        fbb.addFloat64(1, object.amount);
        fbb.addOffset(2, categoryOffset);
        fbb.addOffset(3, descriptionOffset);
        fbb.addInt64(4, object.id ?? 0);
        fbb.finish(fbb.endTable());
        return object.id ?? 0;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final dateParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final amountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final categoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final object = ExpenseEntity(
          id: idParam,
          date: dateParam,
          amount: amountParam,
          category: categoryParam,
          description: descriptionParam,
        );

        return object;
      },
    ),
    BudgetEntity: obx_int.EntityDefinition<BudgetEntity>(
      model: _entities[1],
      toOneRelations: (BudgetEntity object) => [],
      toManyRelations: (BudgetEntity object) => {},
      getId: (BudgetEntity object) => object.id,
      setId: (BudgetEntity object, int id) {
        object.id = id;
      },
      objectToFB: (BudgetEntity object, fb.Builder fbb) {
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        fbb.startTable(6);
        fbb.addInt64(0, object.id ?? 0);
        fbb.addFloat64(1, object.amount);
        fbb.addInt64(2, object.startDate);
        fbb.addInt64(3, object.endDate);
        fbb.addOffset(4, descriptionOffset);
        fbb.finish(fbb.endTable());
        return object.id ?? 0;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          4,
        );
        final amountParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final startDateParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final endDateParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final object = BudgetEntity(
          id: idParam,
          amount: amountParam,
          startDate: startDateParam,
          endDate: endDateParam,
          description: descriptionParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ExpenseEntity] entity fields to define ObjectBox queries.
class ExpenseEntity_ {
  /// See [ExpenseEntity.date].
  static final date = obx.QueryIntegerProperty<ExpenseEntity>(
    _entities[0].properties[0],
  );

  /// See [ExpenseEntity.amount].
  static final amount = obx.QueryDoubleProperty<ExpenseEntity>(
    _entities[0].properties[1],
  );

  /// See [ExpenseEntity.category].
  static final category = obx.QueryStringProperty<ExpenseEntity>(
    _entities[0].properties[2],
  );

  /// See [ExpenseEntity.description].
  static final description = obx.QueryStringProperty<ExpenseEntity>(
    _entities[0].properties[3],
  );

  /// See [ExpenseEntity.id].
  static final id = obx.QueryIntegerProperty<ExpenseEntity>(
    _entities[0].properties[4],
  );
}

/// [BudgetEntity] entity fields to define ObjectBox queries.
class BudgetEntity_ {
  /// See [BudgetEntity.id].
  static final id = obx.QueryIntegerProperty<BudgetEntity>(
    _entities[1].properties[0],
  );

  /// See [BudgetEntity.amount].
  static final amount = obx.QueryDoubleProperty<BudgetEntity>(
    _entities[1].properties[1],
  );

  /// See [BudgetEntity.startDate].
  static final startDate = obx.QueryIntegerProperty<BudgetEntity>(
    _entities[1].properties[2],
  );

  /// See [BudgetEntity.endDate].
  static final endDate = obx.QueryIntegerProperty<BudgetEntity>(
    _entities[1].properties[3],
  );

  /// See [BudgetEntity.description].
  static final description = obx.QueryStringProperty<BudgetEntity>(
    _entities[1].properties[4],
  );
}
