import 'package:flutter/material.dart';

import 'package:trocado/modules/core/presentation/themes/themes.dart';

ThemeData get light => Themes.theme(lightScheme);

ColorScheme get lightScheme => const ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xff4c662b),
  surfaceTint: Color(0xff4c662b),
  onPrimary: Color(0xffffffff),
  primaryContainer: Color(0xffcdeda3),
  onPrimaryContainer: Color(0xff354e16),
  secondary: Color(0xff586249),
  onSecondary: Color(0xffffffff),
  secondaryContainer: Color(0xffdce7c8),
  onSecondaryContainer: Color(0xff404a33),
  tertiary: Color(0xff386663),
  onTertiary: Color(0xffffffff),
  tertiaryContainer: Color(0xffbcece7),
  onTertiaryContainer: Color(0xff1f4e4b),
  error: Color(0xffba1a1a),
  onError: Color(0xffffffff),
  errorContainer: Color(0xffffdad6),
  onErrorContainer: Color(0xff93000a),
  surface: Color(0xfff9faef),
  onSurface: Color(0xff1a1c16),
  onSurfaceVariant: Color(0xff44483d),
  outline: Color(0xff75796c),
  outlineVariant: Color(0xffc5c8ba),
  shadow: Color(0xff000000),
  scrim: Color(0xff000000),
  inverseSurface: Color(0xff2f312a),
  inversePrimary: Color(0xffb1d18a),
  primaryFixed: Color(0xffcdeda3),
  onPrimaryFixed: Color(0xff102000),
  primaryFixedDim: Color(0xffb1d18a),
  onPrimaryFixedVariant: Color(0xff354e16),
  secondaryFixed: Color(0xffdce7c8),
  onSecondaryFixed: Color(0xff151e0b),
  secondaryFixedDim: Color(0xffbfcbad),
  onSecondaryFixedVariant: Color(0xff404a33),
  tertiaryFixed: Color(0xffbcece7),
  onTertiaryFixed: Color(0xff00201e),
  tertiaryFixedDim: Color(0xffa0d0cb),
  onTertiaryFixedVariant: Color(0xff1f4e4b),
  surfaceDim: Color(0xffdadbd0),
  surfaceBright: Color(0xfff9faef),
  surfaceContainerLowest: Color(0xffffffff),
  surfaceContainerLow: Color(0xfff3f4e9),
  surfaceContainer: Color(0xffeeefe3),
  surfaceContainerHigh: Color(0xffe8e9de),
  surfaceContainerHighest: Color(0xffe2e3d8),
);

ThemeData get lightMediumContrast => Themes.theme(lightMediumContrastScheme);

ColorScheme get lightMediumContrastScheme => const ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xff253d05),
  surfaceTint: Color(0xff4c662b),
  onPrimary: Color(0xffffffff),
  primaryContainer: Color(0xff5a7539),
  onPrimaryContainer: Color(0xffffffff),
  secondary: Color(0xff303924),
  onSecondary: Color(0xffffffff),
  secondaryContainer: Color(0xff667157),
  onSecondaryContainer: Color(0xffffffff),
  tertiary: Color(0xff083d3a),
  onTertiary: Color(0xffffffff),
  tertiaryContainer: Color(0xff477572),
  onTertiaryContainer: Color(0xffffffff),
  error: Color(0xff740006),
  onError: Color(0xffffffff),
  errorContainer: Color(0xffcf2c27),
  onErrorContainer: Color(0xffffffff),
  surface: Color(0xfff9faef),
  onSurface: Color(0xff0f120c),
  onSurfaceVariant: Color(0xff34382d),
  outline: Color(0xff505449),
  outlineVariant: Color(0xff6b6f62),
  shadow: Color(0xff000000),
  scrim: Color(0xff000000),
  inverseSurface: Color(0xff2f312a),
  inversePrimary: Color(0xffb1d18a),
  primaryFixed: Color(0xff5a7539),
  onPrimaryFixed: Color(0xffffffff),
  primaryFixedDim: Color(0xff425c23),
  onPrimaryFixedVariant: Color(0xffffffff),
  secondaryFixed: Color(0xff667157),
  onSecondaryFixed: Color(0xffffffff),
  secondaryFixedDim: Color(0xff4e5840),
  onSecondaryFixedVariant: Color(0xffffffff),
  tertiaryFixed: Color(0xff477572),
  onTertiaryFixed: Color(0xffffffff),
  tertiaryFixedDim: Color(0xff2e5c59),
  onTertiaryFixedVariant: Color(0xffffffff),
  surfaceDim: Color(0xffc6c7bd),
  surfaceBright: Color(0xfff9faef),
  surfaceContainerLowest: Color(0xffffffff),
  surfaceContainerLow: Color(0xfff3f4e9),
  surfaceContainer: Color(0xffe8e9de),
  surfaceContainerHigh: Color(0xffdcded3),
  surfaceContainerHighest: Color(0xffd1d3c8),
);

ThemeData get lightHighContrast => Themes.theme(lightHighContrastScheme);

ColorScheme get lightHighContrastScheme => const ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xff1c3200),
  surfaceTint: Color(0xff4c662b),
  onPrimary: Color(0xffffffff),
  primaryContainer: Color(0xff375018),
  onPrimaryContainer: Color(0xffffffff),
  secondary: Color(0xff262f1a),
  onSecondary: Color(0xffffffff),
  secondaryContainer: Color(0xff434c35),
  onSecondaryContainer: Color(0xffffffff),
  tertiary: Color(0xff003230),
  onTertiary: Color(0xffffffff),
  tertiaryContainer: Color(0xff21504e),
  onTertiaryContainer: Color(0xffffffff),
  error: Color(0xff600004),
  onError: Color(0xffffffff),
  errorContainer: Color(0xff98000a),
  onErrorContainer: Color(0xffffffff),
  surface: Color(0xfff9faef),
  onSurface: Color(0xff000000),
  onSurfaceVariant: Color(0xff000000),
  outline: Color(0xff2a2d24),
  outlineVariant: Color(0xff474b40),
  shadow: Color(0xff000000),
  scrim: Color(0xff000000),
  inverseSurface: Color(0xff2f312a),
  inversePrimary: Color(0xffb1d18a),
  primaryFixed: Color(0xff375018),
  onPrimaryFixed: Color(0xffffffff),
  primaryFixedDim: Color(0xff213903),
  onPrimaryFixedVariant: Color(0xffffffff),
  secondaryFixed: Color(0xff434c35),
  onSecondaryFixed: Color(0xffffffff),
  secondaryFixedDim: Color(0xff2c3620),
  onSecondaryFixedVariant: Color(0xffffffff),
  tertiaryFixed: Color(0xff21504e),
  onTertiaryFixed: Color(0xffffffff),
  tertiaryFixedDim: Color(0xff033937),
  onTertiaryFixedVariant: Color(0xffffffff),
  surfaceDim: Color(0xffb8baaf),
  surfaceBright: Color(0xfff9faef),
  surfaceContainerLowest: Color(0xffffffff),
  surfaceContainerLow: Color(0xfff1f2e6),
  surfaceContainer: Color(0xffe2e3d8),
  surfaceContainerHigh: Color(0xffd4d5ca),
  surfaceContainerHighest: Color(0xffc6c7bd),
);
